create database GroceryStore;
use Grocerystore;
show tables;

CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

	CREATE TABLE IF NOT EXISTS order_details (
		ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
		ord_id SMALLINT,
		prod_id TINYINT,
		quantity TINYINT,
		each_price DECIMAL(10,2),
		total_price DECIMAL(10,2),
		FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
			ON UPDATE CASCADE ON DELETE CASCADE,
		FOREIGN KEY (prod_id) REFERENCES products(prod_id)
			ON UPDATE CASCADE ON DELETE CASCADE
	);
    

select * from categories;
select * from customers;
select * from employees;
select * from orders;
select * from supplier;
select * from products;
select * from order_details;

## 1. Customer Insights

-- 1. How many unique customer have placed orders?
select count(distinct cust_id) 
from orders;

-- 2. Which customers have placed the highest number of orders?
select cust_id, count(ord_id) as Total_orders
from orders
group by cust_id
order by Total_orders desc;

-- 3. What is the total and average purchase value per customer?
select C.cust_id,
	SUM(Od.total_price) as total_spend,
    AVG(Od.total_price) as average_spend
from customers C
join orders O
on C.cust_id = O.cust_id
join order_details Od
on O.ord_id = Od.ord_id
group by C.cust_id;

-- 4. Who are the top 5 customers by total purchase amount?
select C.cust_id,
sum(Od.total_price) as total_spend from customers C
join orders O
on C.cust_id = O.cust_id
join order_details Od
on O.ord_id = Od.ord_id
group by C.cust_id
order by total_spend desc
limit 5;

## 2. Product Performance
select * from products;

-- 1. What is the average price of products by category?
select cat_id,
avg(price) from products
group by cat_id;

-- 2. why product have the highest total sales volume (by quantity)?
select * from order_details;

select prod_id, sum(quantity)
from order_details
group by prod_id
order by sum(quantity) desc;

-- 3. What is the total revenue generated by each product?
select * from products;

select prod_id, sum(total_price)
from order_details
group by prod_id;

## 3. Supplier Contribution

-- 1. How many suppliers are there in the database?
select * from supplier;
select count(sup_id) from supplier;

-- 2. Which supplier provides the most products?
select sup_id, count(prod_id)
from products
group by sup_id
order by count(prod_id) desc;

-- 3. What is the average price of products from each supplier?
select *from products;

select sup_id,
avg(price) from products
group by sup_id;

-- 4. Which suppliers contribute the most to total product sales (by revenue)?
select * from products;
select * from order_details;

select P.sup_id,
	sum(Od.total_price)
from products as P
join order_details as Od
on P.prod_id = Od.prod_id
group by P.sup_id
order by sum(Od.total_price) desc;

## 4. Sales and Order trends.
select * from orders;

-- 1. How many orders have been placed in total?
select count(*) from orders;

-- 2. What is the average value per order?
select * from order_details;

select avg(total_price) as average_value
from order_details;

-- 3. How do order patterns vary across weekdays and weekends?
select dayname(order_date) as day_name,
	count(*) as total_orders
from orders
group by dayname(order_date);

## 5. Employee Performance
select * from employees;

-- 1. How many employees have processed orders?
select * from orders;

select count(distinct emp_id) from orders;

-- 2. Which employees have handled the most orders?

select emp_id, count(ord_id) as total_order
from orders
group by emp_id
order by total_order;

-- 3. What is the total sales value processed by each employee?
select e.emp_name, SUM(OD.total_price) as Total_sales
from employees e
join orders O
on e.emp_id = O.emp_id
join order_details OD
on O.ord_id = OD.ord_id
group by e.emp_id
order by Total_sales desc;

-- 4.  What is the average order value handled per employee?
select e.emp_id, avg(Od.total_price) as avgerage_sales
from employees e
join orders O
on e.emp_id = O.emp_id
join order_details Od
on O.ord_id = Od.ord_id
group by e.emp_id;

## 6. Order Details Deep Drive

-- 1. What is the relationship between quantity ordered and total price?
select quantity, total_price from order_details;

-- 2. The relationship between quantity ordered and average price?
select quantity, avg(total_price) as avg_price 
from order_details
group by quantity
order by quantity;

-- How does the unit price vary across products and orders?
select * from order_details;
select ord_id,
	prod_id,
    each_price
from order_details;
-- Product-wise avg unit price
select prod_id,
	avg(each_price) as average_price
from order_details
group by prod_id;
